version: '3.1'

services:
  beelogger:
    image: ghcr.io/programmier-ag/beelogger-provider:latest
    # Uncomment if you'd like to build the image yourself.
    # build: .
    restart: "always"
    ports:
      - "2667:8000"
    volumes:
      - "./data:/app/persistant"
    environment:
      DEFAULT_PASS: ""  # SET YOUR INITIAL PASSWORD HERE